version: '3'

services:
  postgres:
    image: postgres
    networks:
      - dashboard
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=postgres

  frontend:
    image: pclub/dashboard:frontend
    ports:
      - "20000:80"

  timetable:
    image: pclub/dashboard:timetable
    networks:
      - dashboard
    links:
      - postgres
    environment:
      - TIME_TABLE_PG_HOST=postgres
      - TIME_TABLE_PG_USERNAME=postgres
      - TIME_TABLE_PG_DB=postgres
      - TIME_TABLE_SECRET=dashboard-http

  aggregator:
    image: pclub/dashboard:share-auto-aggrgator
    networks:
      - dashboard
    links:
      - postgres
    environment:
      - SHARE_AUTO_ACCESS_TOKEN=foobar
      - SHARE_AUTO_GROUP_ID=433290100027449
      - SHARE_AUTO_USERNAME=postgres
      - SHARE_AUTO_PASSWORD=
      - SHARE_AUTO_HOST=postgres
      - SHARE_AUTO_DATABASE=postgres
      - SHARE_AUTO_SLEEP_TIME=3600

  sharerpc:
    image: pclub/dashoard:share-auto-rpc
    networks:
      - dashboard
    links:
      - postgres
    environment:
      - SHARE_AUTO_RPC_SERVER_PORT=6800
      - SHARE_AUTO_PGHOST=postgres
      - SHARE_AUTO_PGUSER=postgres
      - SHARE_AUTO_PGDATABASE=postgres
      - SHARE_AUTO_PGPASSWORD=
      - SHARE_AUTO_PGPORT=5432

  server:
    image: pclub/dashboard:http
    ports:
      - "20001:8080"
    networks:
      - dashboard
    links:
      - postgres
      - sharerpc
      - timetable
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=
      - DASHBOARD_HTTP_PORT=8080
      - DASHBOARD_SECRET_VALUE="foobar"
      - DASHBOARD_DATABASE=production
      - DASHBOARD_SHARE_HOST=sharerpc
      - DASHBOARD_SHARE_PORT=6800
      - DASHBOARD_TIMETABLE_HOST=timetable
      - DASHBOARD_TIMETABLE_PORT=60002

volumes:
  data:

networks:
  dashboard:
